version: 2.1
orbs:
  node: circleci/node@5.0.2
workflows:
  test:
    jobs:
      - test
jobs:
  test:
    docker:
      - image: cimg/node:lts
    # To use Remote Caching, uncomment the next lines and follow the steps below.
    # environment:
    #  TURBO_TOKEN: $TURBO_TOKEN
    #  TURBO_TEAM: $TURBO_TEAM
    steps:
      - checkout
      - run:
          name: Install pnpm
          command: npm i -g pnpm
      - run:
          name: Install dependencies
          command: pnpm i
      - run:
          name: Run linter
          command: pnpm run lint
      - run:
          name: Run tests
          command: pnpm run test
